#!/bin/bash
rm -r ./src/logs
# Run this file to run all the tests, once
#./test/libs/bats/bin/bats test/*.bats
#./test/libs/bats/bin/bats test/test_apt_install_git.bats
#./test/libs/bats/bin/bats test/test_ask_user_choice.bats
#./test/libs/bats/bin/bats test/test_snap_install_anki.bats
#./test/libs/bats/bin/bats test/test_apt_install_autokey_gtk.bats
#./test/libs/bats/bin/bats test/test_apt_install_keepass2.bats
#./test/libs/bats/bin/bats test/test_apt_install_privoxy.bats
#./test/libs/bats/bin/bats test/test_apt_install_openvpn3.bats
#./test/libs/bats/bin/bats test/test_apt_install_searchmonkey.bats
#./test/libs/bats/bin/bats test/test_apt_install_texlive_xetex.bats
#./test/libs/bats/bin/bats test/test_apt_install_texmaker.bats
#./test/libs/bats/bin/bats test/test_apt_install_wine.bats
#./test/libs/bats/bin/bats test/test_snap_install_notepad_plus_plus.bats
#./test/libs/bats/bin/bats test/test_custom_install_anaconda.bats
#./test/libs/bats/bin/bats test/test_custom_install_energizedprotection_social_0.bats
#./test/libs/bats/bin/bats test/test_custom_install_energizedprotection_social_1.bats
#./test/libs/bats/bin/bats test/test_custom_install_energizedprotection_social_2_1.bats
#./test/libs/bats/bin/bats test/test_custom_install_energizedprotection_social_2_2.bats
#./test/libs/bats/bin/bats test/test_custom_install_energizedprotection_social_2_3.bats
#./test/libs/bats/bin/bats test/test_custom_install_energizedprotection_social_3_1.bats
#./test/libs/bats/bin/bats test/test_custom_install_energizedprotection_social_3_2.bats
#./test/libs/bats/bin/bats test/test_custom_install_energizedprotection_social_3_3.bats
#./test/libs/bats/bin/bats test/test_custom_install_energizedprotection_social_3_4.bats
#./test/libs/bats/bin/bats test/test_custom_install_energizedprotection_social_3_5.bats
#./test/libs/bats/bin/bats test/test_custom_install_energizedprotection_social_3_6.bats
#./test/libs/bats/bin/bats test/test_custom_install_energizedprotection_social_4_1.bats
#./test/libs/bats/bin/bats test/test_custom_install_energizedprotection_social_4_2.bats
#./test/libs/bats/bin/bats test/test_custom_install_energizedprotection_social_5.bats
#./test/libs/bats/bin/bats test/test_custom_install_energizedprotection_social_6.bats
#./test/libs/bats/bin/bats test/test_custom_install_energizedprotection_social_7.bats
#./test/libs/bats/bin/bats test/test_custom_install_energizedprotection_social_8.bats
#./test/libs/bats/bin/bats test/test_custom_install_energizedprotection_social_9_1.bats
#./test/libs/bats/bin/bats test/test_custom_install_energizedprotection_social_9_2.bats
#./test/libs/bats/bin/bats test/test_custom_install_energizedprotection_social_9_3.bats
#./test/libs/bats/bin/bats test/test_custom_install_energizedprotection_social_10_1.bats
#./test/libs/bats/bin/bats test/test_custom_install_energizedprotection_social_10_2.bats
#./test/libs/bats/bin/bats test/test_custom_install_energizedprotection_social_11_1.bats
#./test/libs/bats/bin/bats test/test_custom_install_energizedprotection_social_11_2.bats
#
#./test/libs/bats/bin/bats test/test_custom_install_energizedprotection_porn_0.bats
#./test/libs/bats/bin/bats test/test_custom_install_energizedprotection_porn_1.bats
#./test/libs/bats/bin/bats test/test_custom_install_energizedprotection_porn_2_1.bats
#./test/libs/bats/bin/bats test/test_custom_install_energizedprotection_porn_2_2.bats
#./test/libs/bats/bin/bats test/test_custom_install_energizedprotection_porn_2_3.bats
#./test/libs/bats/bin/bats test/test_custom_install_energizedprotection_porn_3_1.bats
#./test/libs/bats/bin/bats test/test_custom_install_energizedprotection_porn_3_2.bats
#./test/libs/bats/bin/bats test/test_custom_install_energizedprotection_porn_3_3.bats
#./test/libs/bats/bin/bats test/test_custom_install_energizedprotection_porn_3_4.bats
#./test/libs/bats/bin/bats test/test_custom_install_energizedprotection_porn_3_5.bats
#./test/libs/bats/bin/bats test/test_custom_install_energizedprotection_porn_3_6.bats
#./test/libs/bats/bin/bats test/test_custom_install_energizedprotection_porn_4_1.bats
#./test/libs/bats/bin/bats test/test_custom_install_energizedprotection_porn_4_2.bats
#./test/libs/bats/bin/bats test/test_custom_install_energizedprotection_porn_5.bats
#./test/libs/bats/bin/bats test/test_custom_install_energizedprotection_porn_6.bats
#./test/libs/bats/bin/bats test/test_custom_install_energizedprotection_porn_7.bats
#./test/libs/bats/bin/bats test/test_custom_install_energizedprotection_porn_8.bats
#./test/libs/bats/bin/bats test/test_custom_install_energizedprotection_porn_9_1.bats
#./test/libs/bats/bin/bats test/test_custom_install_energizedprotection_porn_9_2.bats
#./test/libs/bats/bin/bats test/test_custom_install_energizedprotection_porn_9_3.bats
#./test/libs/bats/bin/bats test/test_custom_install_energizedprotection_porn_10_1.bats
#./test/libs/bats/bin/bats test/test_custom_install_energizedprotection_porn_10_2.bats
#./test/libs/bats/bin/bats test/test_custom_install_energizedprotection_porn_11_1.bats
#./test/libs/bats/bin/bats test/test_custom_install_energizedprotection_porn_11_2.bats

#
./test/libs/bats/bin/bats test/test_custom_install_energizedprotection_additional_0.bats
./test/libs/bats/bin/bats test/test_custom_install_energizedprotection_additional_1.bats
./test/libs/bats/bin/bats test/test_custom_install_energizedprotection_additional_2_1.bats
./test/libs/bats/bin/bats test/test_custom_install_energizedprotection_additional_2_2.bats
./test/libs/bats/bin/bats test/test_custom_install_energizedprotection_additional_2_3.bats
./test/libs/bats/bin/bats test/test_custom_install_energizedprotection_additional_3_1.bats
./test/libs/bats/bin/bats test/test_custom_install_energizedprotection_additional_3_2.bats
./test/libs/bats/bin/bats test/test_custom_install_energizedprotection_additional_3_3.bats
./test/libs/bats/bin/bats test/test_custom_install_energizedprotection_additional_3_4.bats
./test/libs/bats/bin/bats test/test_custom_install_energizedprotection_additional_3_5.bats
./test/libs/bats/bin/bats test/test_custom_install_energizedprotection_additional_3_6.bats
./test/libs/bats/bin/bats test/test_custom_install_energizedprotection_additional_4_1.bats
./test/libs/bats/bin/bats test/test_custom_install_energizedprotection_additional_4_2.bats
./test/libs/bats/bin/bats test/test_custom_install_energizedprotection_additional_5.bats
./test/libs/bats/bin/bats test/test_custom_install_energizedprotection_additional_6.bats
./test/libs/bats/bin/bats test/test_custom_install_energizedprotection_additional_7.bats
./test/libs/bats/bin/bats test/test_custom_install_energizedprotection_additional_8.bats
./test/libs/bats/bin/bats test/test_custom_install_energizedprotection_additional_9_1.bats
./test/libs/bats/bin/bats test/test_custom_install_energizedprotection_additional_9_2.bats
./test/libs/bats/bin/bats test/test_custom_install_energizedprotection_additional_9_3.bats
./test/libs/bats/bin/bats test/test_custom_install_energizedprotection_additional_10_1.bats
./test/libs/bats/bin/bats test/test_custom_install_energizedprotection_additional_10_2.bats
./test/libs/bats/bin/bats test/test_custom_install_energizedprotection_additional_11_1.bats
./test/libs/bats/bin/bats test/test_custom_install_energizedprotection_additional_11_2.bats